# Default values for order-service
replicaCount: 2

image:
  repository: ghcr.io/akshu0814/sre-platform/order-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: orders.restaurant.com

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

livenessProbe:
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 5

env:
  NODE_ENV: production
  PORT: "3000"